version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  ml-client:
    build: ./machine-learning-client
    depends_on:
      - mongodb

  web:
    build: ./web-app
    ports:
      - "5050:5000"
    depends_on:
      - mongodb